### ISSUE TITLE
Wrote a new version which uses the `EventStore.Client.Grpc.Streams` package

### ISSUE THREAD

**Issue by miran248** [alexeyzimarev/Proto.Persistence.EventStore#1]
I've created a new version using `EventStore.Client.Grpc.Streams` instead of `EventStore.ClientAPI.NetCore` and `System.Text.Json` instead of `Newtonsoft.Json`.

https://gist.github.com/miran248/de009f37513d1fffb5817cc5fd93e0b4
(haven't tested the snapshots yet but the events are working)

Since it uses different dependencies, we'd need to either make a breaking change in this one or create a new, separate package.
Also, it currently uses json but that should be configurable, i think.

**Comment by alexeyzimarev** [comment]
Done :)
